### ISSUE TITLE
Create and edit issues programatically

### ISSUE THREAD

**Issue by saraf** [CollaboRateMgmt/CollaboRate#3]
POC needed to create and edit github issues programmatically from client-side javascript code running in browser.

**Comment by sohrabsaran** [comment]
Does this task specify the creation of a function? No

  Is this task a 'requirement', or is it a 'simple use case'?  requirement

   First subtask 
  Summary 
 Authenticate oneself in order to read, create and edit issues programmatically
 
Description 
 Use some github rest api wrapper to authenticate oneself in order to read, create and edit issues programmatically. Subsequent multiple calls to read, create and edit github issues should not need us as programmers to keep passing the authentication info on every call.
 
  

 Second subtask 
  Summary 
 Create and edit issues programatically using github rest api wrapper once authentication is successfully done.
 
Description 
 After using some github rest api wrapper to authenticate oneself in order to read, create and edit issues programmatically, Make subsequent multiple calls to  create and edit github issues, that should need us as programmers to just some reference to the successful authentication attempt for every other call to create and edit github issues.
